# Generated by Django 3.2 on 2023-06-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='product_images')),
                ('productioncost', models.FloatField(default=0.0)),
                ('transportcost', models.FloatField(default=0.0)),
                ('additionalcost', models.FloatField(default=0.0)),
                ('totalcost', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
