# Generated by Django 3.2 on 2023-06-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qcode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
