# Generated by Django 3.2 on 2023-06-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_qcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
