# Generated by Django 3.2 on 2023-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_productreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreturn',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
