# Generated by Django 3.2 on 2023-06-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
