# Generated by Django 3.2 on 2023-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_notifications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('short', 'Shirt'), ('pant', 'Pant'), ('tshirt', 'T shirt')], max_length=50),
        ),
    ]
