# Generated by Django 3.2 on 2023-06-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('tshirt', 'T shirt')], max_length=50),
        ),
    ]
