# Generated by Django 3.2 on 2023-06-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='is_order',
        ),
    ]
