# Generated by Django 3.2 on 2023-06-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_productorder_is_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorder',
            name='product',
            field=models.ManyToManyField(related_name='productorder', to='pos.ProductOrder'),
        ),
    ]
