# Generated by Django 3.2 on 2023-06-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_sellorder_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('paymentstatus', models.CharField(choices=[('approve', 'Approve'), ('pending', 'Pending'), ('cashondelivery', 'Cash On Delivery')], default='approve', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.sellorder')),
            ],
        ),
    ]
