# Generated by Django 3.2 on 2023-06-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_sell_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
